netG:
  _target_: vc_tts_template.fastspeech2wGMM.FastSpeech2wGMM
  max_seq_len: 1000
  num_vocab: 52
  encoder_hidden_dim: 256
  encoder_num_layer: 4
  encoder_num_head: 2
  conv_filter_size: 1024
  conv_kernel_size: [9, 1]
  encoder_dropout: 0.2
  prosody_emb_dim: 256
  extra_conv_kernel_size: 3
  extra_conv_n_layers: 2
  gru_hidden_dim: 256
  gru_n_layers: 2
  pp_conv_out_channels: 256
  pp_conv_kernel_size: 3
  pp_conv_n_layers: 2
  pp_conv_dropout: 0.2
  pp_zoneout: 0.1
  num_gaussians: 20
  variance_predictor_filter_size: 256
  variance_predictor_kernel_size: 3
  variance_predictor_dropout: 0.5
  pitch_feature_level:
  energy_feature_level:
  pitch_quantization: "linear"
  energy_quantization: "linear"
  n_bins: 256
  decoder_hidden_dim: 256
  decoder_num_layer: 6
  decoder_num_head: 2
  decoder_dropout: 0.2
  n_mel_channel:
  encoder_fix: False
  stats: {"pitch_min": 70, "pitch_max": 750, "energy_min": 10, "energy_max": 27}
  speakers:
  emotions:
