netG:
  _target_: vc_tts_template.fastspeech2VC.fastspeech2VC
  n_mel_channel:
  # encoder_decoder
  attention_dim: 384
  encoder_hidden_dim: 256
  encoder_num_layer: 4
  encoder_num_head: 2
  decoder_hidden_dim: 256
  decoder_num_layer: 4
  decoder_num_head: 2
  conv_kernel_size: 7
  ff_expansion_factor: 4
  conv_expansion_factor: 2
  ff_dropout: 0.2
  attention_dropout: 0.2
  conv_dropout: 0.2
  # varianceadaptor
  variance_predictor_filter_size: 256
  variance_predictor_kernel_size_d: 3
  variance_predictor_layer_num_d: 2
  variance_predictor_kernel_size_p: 5
  variance_predictor_layer_num_p: 5
  variance_predictor_kernel_size_e: 3
  variance_predictor_layer_num_e: 2
  variance_predictor_dropout: 0.5
  stop_gradient_flow_d: False
  stop_gradient_flow_p: True
  stop_gradient_flow_e: False
  reduction_factor:

  encoder_fix: False
  speakers: {'jvs034': 0,
 'jvs002': 1,
 'jvs026': 2,
 'jvs056': 3,
 'JSUT': 4,
 'JSSS': 5,
 'jvs081': 6,
 'jvs012': 7,
 'jvs096': 8,
 'jvs052': 9,
 'jvs088': 10,
 'jvs057': 11,
 'jvs045': 12,
 'jvs010': 13,
 'jvs060': 14,
 'jvs091': 15,
 'jvs068': 16,
 'jvs047': 17,
 'jvs094': 18,
 'jvs071': 19,
 'jvs063': 20,
 'jvs087': 21,
 'jvs049': 22,
 'jvs007': 23,
 'jvs032': 24,
 'jvs070': 25,
 'jvs040': 26,
 'jvs013': 27,
 'jvs067': 28,
 'jvs084': 29,
 'jvs042': 30,
 'jvs024': 31,
 'jvs015': 32,
 'jvs095': 33,
 'jvs083': 34,
 'jvs020': 35,
 'jvs090': 36,
 'jvs093': 37,
 'jvs003': 38,
 'jvs038': 39,
 'jvs039': 40,
 'jvs031': 41,
 'jvs016': 42,
 'jvs046': 43,
 'jvs041': 44,
 'jvs055': 45,
 'jvs072': 46,
 'jvs018': 47,
 'jvs099': 48,
 'jvs033': 49,
 'jvs082': 50,
 'jvs069': 51,
 'jvs078': 52,
 'jvs023': 53,
 'jvs050': 54,
 'jvs058': 55,
 'jvs027': 56,
 'jvs004': 57,
 'jvs086': 58,
 'jvs005': 59,
 'jvs011': 60,
 'jvs017': 61,
 'jvs043': 62,
 'jvs051': 63,
 'jvs097': 64,
 'jvs061': 65,
 'jvs079': 66,
 'jvs001': 67,
 'jvs075': 68,
 'jvs029': 69,
 'jvs073': 70,
 'jvs025': 71,
 'jvs048': 72,
 'jvs053': 73,
 'jvs036': 74,
 'jvs014': 75,
 'jvs062': 76,
 'jvs066': 77,
 'jvs064': 78,
 'jvs080': 79,
 'jvs092': 80,
 'jvs077': 81,
 'jvs100': 82,
 'jvs054': 83,
 'jvs028': 84,
 'jvs035': 85,
 'jvs022': 86,
 'jvs098': 87,
 'jvs076': 88,
 'jvs019': 89,
 'jvs009': 90,
 'jvs044': 91,
 'jvs006': 92,
 'jvs021': 93,
 'jvs037': 94,
 'jvs008': 95,
 'jvs085': 96,
 'jvs059': 97,
 'jvs065': 98}
  emotions:
